### ISSUE TITLE
Predict image after train

### ISSUE THREAD

**Issue by hoangthangbk51** [Mewzax/Hcaptcha-AI-Trainer#1]
Please support the code to use predict the image after train. Posible to screenshot the screen have captcha image and then predict this captcha base on the qesition ? .get the coordinates ? . thanks for support.

**Comment by hoangthangbk51** [comment]
After training i try to predict image and get with a problem "'tuple' object is not callable"

**Comment by bigboy-baby** [comment]
> After training i try to predict image and get with a problem "'tuple' object is not callable"

sounds like a you-problem

**Comment by mewzax** [comment]
sounds like a skill issue
